lojaapp/urls.py
from django.urls import path
from .views import *



app_name ="lojaapp"
urlpatterns =[
path("", HomeView.as_view(), name="home"),
path("todos-produtos/", TodosProdutosView.as_view(), name="todosprodutos"),
path("produto/<slug:slug>/",ProdutoDetalhesView.as_view(), name="produtodetalhe"),
path("addcarro-/<int:pro_id>/",AddCarroView.as_view(), name="addcarro"),
path("meu-carro/",MeuCarroView.as_view(), name="meucarro"),
path("manipular-carro/<int:cp_id>",ManipularCarroView.as_view(), name="manipularcarro"),
path("limpar-carro/",LimparCarroView.as_view(), name="limparcarro"),
path("checkout/",CheckoutView.as_view(), name="checkout"),
path("registar/",ClienteRegistarView.as_view(), name="clienteregistar"),
path("sair/",ClienteSairView.as_view(), name="clientesair"),
path("entrar/",ClienteEntrarView.as_view(), name="clienteentrar"),
path("perfil/",ClientePerfilView.as_view(), name="clienteperfil"),
path("perfil/pedido-<int:pk>/",ClientePedidoDetalheView.as_view(), name="clientepedidodetalhe"),
path("admin-login/",AdminLoginView.as_view(), name="adminlogin"),
path("admin-home/",AdminHomeView.as_view(), name="adminhome"),
path("admin-pedido/<int:pk>/",AdminPedidoDetalheView.as_view(), name="adminpedidodetalhe"),
path("admin-todos-pedidos/",AdminPedidoListaView.as_view(), name="adminpedidolista"),
path("admin-pedido-<int:pk>-mudar/",AdminPedidoMudarStatusView.as_view(), name="adminpedidomudar"),
path("pesquisa/",PesquisaView.as_view(), name="pesquisar"),
path("pagamento/",PagamentotView.as_view(), name="pagamento"),

]

lojaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lojaapp.urls')),
]
               


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo =models.CharField(max_length=200) 
    image =models.ImageField(upload_to="admins")
    telefone=models.CharField(max_length=10)
   
    def __str__(self):
        return self.user.username

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo =models.CharField(max_length=200) 
    endereco =models.CharField(max_length=200, null=True,blank=True)
    data_on=models.DateTimeField(auto_now_add=True)
   
    
    def __str__(self):
        return self.nome_completo

class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.titulo

class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='produtos')
    preco_mercado = models.PositiveIntegerField()
    venda =models.PositiveSmallIntegerField()
    descricao = models.TextField()
    garantia = models.CharField(max_length=600,null=True,blank=True)
    return_devolucao = models.CharField(max_length=300,null=True,blank=True)
    visualizacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo

class Carro(models.Model):
     cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True,blank=True)       
     total = models.PositiveIntegerField(default=0) 
     criado_em=models.DateTimeField(auto_now_add=True)


     def __str__(self):
        return"Carro:" + str(self.id)


class CarroProduto(models.Model):
     carro = models.ForeignKey(Carro,on_delete=models.CASCADE)       
     produto = models.ForeignKey(Produto, on_delete=models.CASCADE)  
     avaliacao = models.PositiveIntegerField()
     quantidade = models.PositiveIntegerField()
     subtotal = models.PositiveIntegerField()

     def __str__(self):
        return"Carro:" + str(self.carro.id)+"CarroProduto:" +str(self.id)

PEDIDO_STATUS=(
    ("Pedido Recebido", " Pedido Recebido"),
    ("Pedido Processando", " Pedido Processando"),
    ("Pedido Caminho", " Pedido Caminho"),
    ("Pedido Completo", " Pedido Completo"),
    ("Pedido Cancelado", " Pedido Cancelado"),
)
METHOD = (
    ("Dinheiro Entrega", "Dinheiro Entrega"),
    ("Khalti","Khalti")
)



class Pedido_order(models.Model):
     carro = models.OneToOneField(Carro,on_delete=models.CASCADE) 
     ordenado_por = models.CharField(max_length=200)
     endereco_envio = models.CharField(max_length=200)
     telefone =models.CharField(max_length=10) 
     email = models.EmailField(null=True,blank=True)
     subtotal = models.PositiveIntegerField()
     desconto = models.PositiveIntegerField() 
     total = models.PositiveIntegerField()
     pedido_status = models.CharField(max_length=50,choices=PEDIDO_STATUS)
     criado_em = models.DateTimeField(auto_now_add=True) 
     pagamento_method = models.CharField(max_length=20,choices=METHOD, default="Dinheiro Entrega")
     pagamento_completo = models.BooleanField(max_length=20, default=False, null = True, blank=True)      
    

     def __str__(self):
        return"Pedido_order:"  +str(self.id)

templates/admin_pagina/adminbase.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock  %}</title>
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
   
</head>
<body>
    <br>
   <div class="container">
    <a href="{% url 'lojaapp:adminhome'%}" class="btn btn-outline-danger">HOME</a>
    <a href="{% url 'lojaapp:adminpedidolista'%}" class="btn btn-outline-danger">TODOS OS PEDIDOS</a>
    <a href="{% url 'lojaapp:home'%}" target="_blank" class="btn btn-outline-danger">VISITAR A LOJA</a>
   </div>

    {% block content %} 
    
    
    
    {% endblock  %}
</body>
</html>

templates/admin_pagina/adminhome.html
{% extends "admin_pagina/adminbase.html" %}
<title>{% block title %}Administrador Home {% endblock  %}</title>



{% block content %} 
<br>
<br>
<h1 class="text-center">Pedidos Recebidos</h1>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
            <th>Código</th>
            <th>Cliente</th>
            <th>ID de Pedido</th>
            <th>Data Pedido</th>
            <th>Valor</th>
        </tr>
        </thead>
        <tbody>
            {% for pedido in PedidosPendentes %}
            
           
        <tr>
            <td>{{forloop.counter}}</td>

            <td>{{pedido.ordenado_por}} </td>
            <td><a href="{% url 'lojaapp:adminpedidodetalhe' pedido.id %}">#Pedido</a>{{pedido.id}}</a></td>
            <td>{{pedido.criado_em}}</td>
            <td>{{pedido.total}}</td>
        </tr>
        {% endfor %}
        
        <tbody>
    </table>
</div>
<style>
*{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
    
}
h2{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: red;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: red;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}

/* Responsive */

@media (max-width: 767px) {
    .fl-table {
        display: block;
        width: 100%;
    }
    .table-wrapper:before{
        content: "Scroll horizontally >";
        display: block;
        text-align: right;
        font-size: 11px;
        color: white;
        padding: 0 0 10px;
    }
    .fl-table thead, .fl-table tbody, .fl-table thead th {
        display: block;
    }
    .fl-table thead th:last-child{
        border-bottom: none;
    }
    .fl-table thead {
        float: left;
    }
    .fl-table tbody {
        width: auto;
        position: relative;
        overflow-x: auto;
    }
    .fl-table td, .fl-table th {
        padding: 20px .625em .625em .625em;
        height: 60px;
        vertical-align: middle;
        box-sizing: border-box;
        overflow-x: hidden;
        overflow-y: auto;
        width: 120px;
        font-size: 13px;
        text-overflow: ellipsis;
    }
    .fl-table thead th {
        text-align: left;
        border-bottom: 1px solid #f7f7f9;
    }
    .fl-table tbody tr {
        display: table-cell;
    }
    .fl-table tbody tr:nth-child(odd) {
        background: none;
    }
    .fl-table tr:nth-child(even) {
        background: transparent;
    }
    .fl-table tr td:nth-child(odd) {
        background: #F8F8F8;
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tr td:nth-child(even) {
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tbody td {
        display: block;
        text-align: center;
    }
}

</style> 
{% endblock  %}

templates/admin_pagina/adminlogin.html
{% extends "base.html" %}

{% block title%} Administrador{% endblock %}



{% block content%}
 <style>
     .errorlist{
         color: red;
         list-style: none;
     }
 </style>


                                        
<div class="container mt-5">
  
    <div  class="row">
        <h3>ADMINISTRADOR</h3>
            <form action="" method="POST">            
                {% csrf_token %}
               {{form.as_p}}
               <button    class="btn btn-primary btn-danger" style="width: 250px; margin-left: 100px;"> Entrar </button>
               {% if error %}
               <li style="color:red;">{{error}}</li>
               {% endif %}
            </form>
          
    </div> 
</div>




{% endblock %}

templates/admin_pagina/adminpedidodetalhe.html
{% extends "admin_pagina/adminbase.html" %}
{% load humanize %}
{% block title%} Detalhe do Pedido{% endblock %}



{% block content %}                                       
<div class="container mt-5">
 <div  class="row">
    <form action="{% url 'lojaapp:adminpedidomudar' pedido_obj.id %}"   method="post">
        {% csrf_token %}
        <select name="status">
        {% for i, j in todosstatus %}
        <option value="{{i}}"{% if i == pedido_obj.pedido_status  %} selected {% endif %}> {{j}}</option>
        {% endfor %}
         
        </select>

     <button class="btn btn-outline-danger"> Alterar Status</button>
    </form>
       <div class="col-md-6">

           <h3 class="text-center ml-5">Detalhe do Pedido</h3>
           <hr>
           <p> <span class="font-weight-bold">Pedido ID : </span>{{pedido_obj.id}}</p>
           <p> <span class="font-weight-bold">Status do Pedido: </span>{{pedido_obj.pedido_status}}</p>
           <p> <span class="font-weight-bold">Data Efetuado: </span>{{pedido_obj.criado_em}}</p>
           <p> <span class="font-weight-bold">Informação Cliente: </span>{{pedido_obj.ordenado_por}}</p>
           <p> <span class="font-weight-bold">Telefone Cliente: </span>{{pedido_obj.telefone}}</p>
           <p> <span class="font-weight-bold">Endereço Cliente: </span>{{pedido_obj.endereco_envio}}</p>   
           <hr>
           
        </div>         
    </div>                                    
<br>
<h1 class="text-center">Items do Pedidos</h1>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
            <th>Código</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Subtotal</th>
        </tr>
        </thead>
        <tbody>
            {% for cp in pedido_obj.carro.carroproduto_set.all %}        
        <tr>
            <td>{{forloop.counter}}</td>
            <td> <a target="blank" href=" {% url 'lojaapp:produtodetalhe' cp.produto.slug %}">{{cp.produto.titulo}}{{cp.produto.id}}</a></td>
            <td>{{cp.avaliacao}}</td>
            <td>{{cp.quantidade}}</td>
            <td>{{cp.subtotal}}</td>
        </tr>
        {% endfor %}
        <tr>
            <th colspan="4" class="text-right">Valor Total</th>
            <th>Moeda: {{pedido_obj.total|intcomma}}</th>
        </tr>
        <tbody>
    </table>
    
</div>
<style>
    
</style>
<style>
*{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
    
}
h2{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: red;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: red;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}

/* Responsive */

@media (max-width: 767px) {
    .fl-table {
        display: block;
        width: 100%;
    }
    .table-wrapper:before{
        content: "Scroll horizontally >";
        display: block;
        text-align: right;
        font-size: 11px;
        color: white;
        padding: 0 0 10px;
    }
    .fl-table thead, .fl-table tbody, .fl-table thead th {
        display: block;
    }
    .fl-table thead th:last-child{
        border-bottom: none;
    }
    .fl-table thead {
        float: left;
    }
    .fl-table tbody {
        width: auto;
        position: relative;
        overflow-x: auto;
    }
    .fl-table td, .fl-table th {
        padding: 20px .625em .625em .625em;
        height: 60px;
        vertical-align: middle;
        box-sizing: border-box;
        overflow-x: hidden;
        overflow-y: auto;
        width: 120px;
        font-size: 13px;
        text-overflow: ellipsis;
    }
    .fl-table thead th {
        text-align: left;
        border-bottom: 1px solid #f7f7f9;
    }
    .fl-table tbody tr {
        display: table-cell;
    }
    .fl-table tbody tr:nth-child(odd) {
        background: none;
    }
    .fl-table tr:nth-child(even) {
        background: transparent;
    }
    .fl-table tr td:nth-child(odd) {
        background: #F8F8F8;
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tr td:nth-child(even) {
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tbody td {
        display: block;
        text-align: center;
    }
}

</style>


{% endblock %}

templates/admin_pagina/adminpedidolista.html
{% extends "admin_pagina/adminbase.html" %}

{% block title%} Todos os Pedidos{% endblock %}

<!DOCTYPE html>

{% block content%}
<br>
<br>
<h1 class="text-center">Todos os Pedidos </h1>
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
        <tr>
            <th>Código</th>
            <th>Cliente</th>
            <th>ID de Pedido</th>
            <th>Data Pedido</th>
            <th>Valor</th>
            <th>Status</th>
        </tr>
        </thead>
        <tbody>
        {% for pedido in todospedidos %}   
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{pedido.ordenado_por}} </td>
            <td><a href="{% url 'lojaapp:adminpedidodetalhe' pedido.id %}">#Pedido</a>{{pedido.id}}</a></td>
            <td>{{pedido.criado_em}}</td>
            <td>{{pedido.total}}</td>
            <td>{{pedido.pedido_status}}</td>
        </tr>
        {% endfor %}
        
        <tbody>
    </table>
</div>
<style>
*{
    box-sizing: border-box;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
}
body{
    font-family: Helvetica;
    -webkit-font-smoothing: antialiased;
    
}
h2{
    text-align: center;
    font-size: 18px;
    text-transform: uppercase;
    letter-spacing: 1px;
    color: white;
    padding: 30px 0;
}

/* Table Styles */

.table-wrapper{
    margin: 10px 70px 70px;
    box-shadow: 0px 35px 50px rgba( 0, 0, 0, 0.2 );
}

.fl-table {
    border-radius: 5px;
    font-size: 12px;
    font-weight: normal;
    border: none;
    border-collapse: collapse;
    width: 100%;
    max-width: 100%;
    white-space: nowrap;
    background-color: white;
}

.fl-table td, .fl-table th {
    text-align: center;
    padding: 8px;
}

.fl-table td {
    border-right: 1px solid #f8f8f8;
    font-size: 12px;
}

.fl-table thead th {
    color: #ffffff;
    background: red;
}


.fl-table thead th:nth-child(odd) {
    color: #ffffff;
    background: red;
}

.fl-table tr:nth-child(even) {
    background: #F8F8F8;
}

/* Responsive */

@media (max-width: 767px) {
    .fl-table {
        display: block;
        width: 100%;
    }
    .table-wrapper:before{
        content: "Scroll horizontally >";
        display: block;
        text-align: right;
        font-size: 11px;
        color: white;
        padding: 0 0 10px;
    }
    .fl-table thead, .fl-table tbody, .fl-table thead th {
        display: block;
    }
    .fl-table thead th:last-child{
        border-bottom: none;
    }
    .fl-table thead {
        float: left;
    }
    .fl-table tbody {
        width: auto;
        position: relative;
        overflow-x: auto;
    }
    .fl-table td, .fl-table th {
        padding: 20px .625em .625em .625em;
        height: 60px;
        vertical-align: middle;
        box-sizing: border-box;
        overflow-x: hidden;
        overflow-y: auto;
        width: 120px;
        font-size: 13px;
        text-overflow: ellipsis;
    }
    .fl-table thead th {
        text-align: left;
        border-bottom: 1px solid #f7f7f9;
    }
    .fl-table tbody tr {
        display: table-cell;
    }
    .fl-table tbody tr:nth-child(odd) {
        background: none;
    }
    .fl-table tr:nth-child(even) {
        background: transparent;
    }
    .fl-table tr td:nth-child(odd) {
        background: #F8F8F8;
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tr td:nth-child(even) {
        border-right: 1px solid #E6E4E4;
    }
    .fl-table tbody td {
        display: block;
        text-align: center;
    }
}

</style> 


{% endblock %}