lojaapp/urls.py
from django.urls import path
from .views import *



app_name ="lojaapp"
urlpatterns =[
path("", HomeView.as_view(), name="home"),
path("todos-produtos/", TodosProdutosView.as_view(), name="todosprodutos"),
path("produto/<slug:slug>/",ProdutoDetalhesView.as_view(), name="produtodetalhe"),
path("addcarro-/<int:pro_id>/",AddCarroView.as_view(), name="addcarro"),
path("meu-carro/",MeuCarroView.as_view(), name="meucarro"),
path("manipular-carro/<int:cp_id>",ManipularCarroView.as_view(), name="manipularcarro"),
path("limpar-carro/",LimparCarroView.as_view(), name="limparcarro"),
path("checkout/",CheckoutView.as_view(), name="checkout"),
path("registar/",ClienteRegistarView.as_view(), name="clienteregistar"),
path("sair/",ClienteSairView.as_view(), name="clientesair"),
path("entrar/",ClienteEntrarView.as_view(), name="clienteentrar"),
path("perfil/",ClientePerfilView.as_view(), name="clienteperfil"),
path("perfil/pedido-<int:pk>/",ClientePedidoDetalheView.as_view(), name="clientepedidodetalhe"),
path("admin-login/",AdminLoginView.as_view(), name="adminlogin"),
path("admin-home/",AdminHomeView.as_view(), name="adminhome"),
path("admin-pedido/<int:pk>/",AdminPedidoDetalheView.as_view(), name="adminpedidodetalhe"),
path("admin-todos-pedidos/",AdminPedidoListaView.as_view(), name="adminpedidolista"),
path("admin-pedido-<int:pk>-mudar/",AdminPedidoMudarStatusView.as_view(), name="adminpedidomudar"),
path("pesquisa/",PesquisaView.as_view(), name="pesquisar"),
path("pagamento/",PagamentotView.as_view(), name="pagamento"),

]

lojaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lojaapp.urls')),
]
               


urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

lojaapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo =models.CharField(max_length=200) 
    image =models.ImageField(upload_to="admins")
    telefone=models.CharField(max_length=10)
   
    def __str__(self):
        return self.user.username

class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo =models.CharField(max_length=200) 
    endereco =models.CharField(max_length=200, null=True,blank=True)
    data_on=models.DateTimeField(auto_now_add=True)
   
    
    def __str__(self):
        return self.nome_completo

class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.titulo

class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='produtos')
    preco_mercado = models.PositiveIntegerField()
    venda =models.PositiveSmallIntegerField()
    descricao = models.TextField()
    garantia = models.CharField(max_length=600,null=True,blank=True)
    return_devolucao = models.CharField(max_length=300,null=True,blank=True)
    visualizacao = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo

class Carro(models.Model):
     cliente = models.ForeignKey(Cliente, on_delete=models.SET_NULL, null=True,blank=True)       
     total = models.PositiveIntegerField(default=0) 
     criado_em=models.DateTimeField(auto_now_add=True)


     def __str__(self):
        return"Carro:" + str(self.id)


class CarroProduto(models.Model):
     carro = models.ForeignKey(Carro,on_delete=models.CASCADE)       
     produto = models.ForeignKey(Produto, on_delete=models.CASCADE)  
     avaliacao = models.PositiveIntegerField()
     quantidade = models.PositiveIntegerField()
     subtotal = models.PositiveIntegerField()

     def __str__(self):
        return"Carro:" + str(self.carro.id)+"CarroProduto:" +str(self.id)

PEDIDO_STATUS=(
    ("Pedido Recebido", " Pedido Recebido"),
    ("Pedido Processando", " Pedido Processando"),
    ("Pedido Caminho", " Pedido Caminho"),
    ("Pedido Completo", " Pedido Completo"),
    ("Pedido Cancelado", " Pedido Cancelado"),
)
METHOD = (
    ("Dinheiro Entrega", "Dinheiro Entrega"),
    ("Khalti","Khalti")
)



class Pedido_order(models.Model):
     carro = models.OneToOneField(Carro,on_delete=models.CASCADE) 
     ordenado_por = models.CharField(max_length=200)
     endereco_envio = models.CharField(max_length=200)
     telefone =models.CharField(max_length=10) 
     email = models.EmailField(null=True,blank=True)
     subtotal = models.PositiveIntegerField()
     desconto = models.PositiveIntegerField() 
     total = models.PositiveIntegerField()
     pedido_status = models.CharField(max_length=50,choices=PEDIDO_STATUS)
     criado_em = models.DateTimeField(auto_now_add=True) 
     pagamento_method = models.CharField(max_length=20,choices=METHOD, default="Dinheiro Entrega")
     pagamento_completo = models.BooleanField(max_length=20, default=False, null = True, blank=True)      
    

     def __str__(self):
        return"Pedido_order:"  +str(self.id)

templates/addcarro.html
{% extends 'base.html' %}
{% block title%}CARRINHO{% endblock %}

{% block content %}
 <div class="container">
     Produto adicionado no carrinho
 </div>          





{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
        <link rel ="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">  
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <title>{% block title%} {% endblock %}</title>
    </head>
    <body>
        <div class="container mt-3" >
            <a href="{% url 'lojaapp:home'%}" class="btn btn-outline-danger">PÁGINA PRINCIPAL</a>
            <a href="{% url 'lojaapp:todosprodutos'%}" class="btn btn-outline-danger">CATEGORIAS</a>
            <a href="{% url 'lojaapp:meucarro'%}" class="btn btn-outline-danger">CARRINHO</a>
            {% if request.user.cliente %}
            seja bem vindo {{request.user.username}}
            <a href="{% url 'lojaapp:clienteperfil'%}" class="btn btn-outline-danger">Meu Perfil</a>
            <a href="{% url 'lojaapp:clientesair'%}" class="btn btn-outline-danger">Sair</a>   
            {% else %}
            <a href="{% url 'lojaapp:clienteregistar'%}" class="btn btn-outline-danger">REGISTO CLIENTE</a>
            <a href="{% url 'lojaapp:clienteentrar'%}" class="btn btn-outline-danger">ENTRAR</a>
            <a href="{% url 'lojaapp:adminlogin'%}" class="btn btn-outline-danger">ADMINISTRADOR</a>
            {% endif %}
            <div  class="float-lg-right">
                <form action="{% url 'lojaapp:pesquisar' %}"  autocomplete="on" method="GET">
                <input  name="keyword" type="text" placeholder="pesquisar produto" style=" height: 35px;"   required>
                <button class="btn btn-outline-danger">Pesquisa</button>
                </form>
            </div> 
      </div>
      <hr>
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/clienteentrar.html
{% extends "base.html" %}

{% block title%} Registo Cliente {% endblock %}



{% block content%}
 <style>
     .errorlist{
         color: red;
         list-style: none;
     }
 </style>


                                        
<div class="container mt-5">
  
    <div  class="row">
        <h3>Entar</h3>
            <form  method="POST">            
               {% csrf_token %}
               {{form.as_p}}
               <button   class="btn btn-primary btn-danger" style="width: 250px; margin-left: 100px;"> Entrar</button>
               {% if error %}
               <li style="color:red;">{{error}}</li>
               {% endif %}
            </form>
            <p>se não tem registo faça o seu registo<a href="{% url 'lojaapp:clienteregistar'%} {% if request.GET.next %}?next={{request.GET.next}}{% endif %}">Registo </p></a> 
    </div> 
</div>




{% endblock %}

templates/clientepedidodetalhe.html
{% extends "base.html" %}
{% load humanize %}
{% block title%} Detalhe do Pedido {% endblock %}



{% block content%}
 <style>
     .errorlist{
         color: red;
         list-style: none;
     }
 </style>


                                        
<div class="container mt-5">
  <div  class="row">
        <div class="col-md-6">

            <h3>Detalhe do Pedido</h3>
            <hr>
            <p> <span class="font-weight-bold">Pedido ID : </span>{{pedido_obj.id}}</p>
            <p> <span class="font-weight-bold">Status do Pedido: </span>{{pedido_obj.pedido_status}}</p>
            <p> <span class="font-weight-bold">Data Efetuado: </span>{{pedido_obj.criado_em}}</p>
            <p> <span class="font-weight-bold">Informação Cliente: </span>{{pedido_obj.ordenado_por}}</p>
            <p> <span class="font-weight-bold">Telefone Cliente: </span>{{pedido_obj.telefone}}</p>
            <p> <span class="font-weight-bold">Endereço Cliente: </span>{{pedido_obj.endereco_envio}}</p>   
            <hr>
            <h4> Items do Pedido</h4>
            <table class="table">
                <thead>
                        <tr>
                            <th>Código</th>
                            <th>Produto</th>
                            <th>Avaliação</th>
                            <th>Quantidade</th>
                            <th>Subtotal</th>
                        </tr>
                </thead>
                    <tbody>
                        {% for cp in pedido_obj.carro.carroproduto_set.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> <a target="blank" href=" {% url 'lojaapp:produtodetalhe' cp.produto.slug %}">{{cp.produto.titulo}}{{cp.produto.id}}</a></td>
                                <td>{{cp.avaliacao}}</td>
                                <td>{{cp.quantidade}}</td>
                                <td>{{cp.subtotal}}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <th colspan="4" class="text-right">Valor Total</th>
                            <th>Moeda: {{pedido_obj.total|intcomma}}</th>
                        </tr>
                       
                    </tbody>
            </table>
        </div>
        
    </div> 
</div>




{% endblock %}

templates/clienteperfil.html
{% extends "base.html" %}

{% block title%} Perfil  Cliente {% endblock %}



{% block content%}
 <style>
     .errorlist{
         color: red;
         list-style: none;
     }
 </style>


                                        
<div class="container mt-5">
  <div  class="row">
      <div class="col-md-6">
        <h3>Dados  do Cliente</h3>
          <p> <span class="font-weight-bold">Nome:</span>{{cliente.nome_completo}}</p>
          <p> <span class="font-weight-bold">Utilizador:</span>{{cliente.user.username}}</p>
          <p> <span class="font-weight-bold">Email:</span>{{cliente.user.email}}</p>
          <p> <span class="font-weight-bold">Endereco:</span>{{cliente.endereco}}</p>
          <p> <span class="font-weight-bold">Registado:</span>{{cliente.data_on}}</p>
      </div>
        <div class="col-md-6 ">
            <h3>Compras</h3>
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>Pedido</th>
                        <th>Valor</th>
                        <th>Data Pedido</th>
                        <th>Status</th>
                    </tr>
                </thead> 
                <tbody>
                    {% for pedidos in pedidos %}
                      <tr>
                          <td>{{forloop.counter}}</td>
                         

                          <td> <a href="{% url 'lojaapp:clientepedidodetalhe' pedidos.pk %}">numero do pedido{{pedidos.id}} </a></td>
                          <td>{{pedidos.total }}</td>
                          <td>{{pedidos.criado_em}}</td>
                          <td>{{pedidos.pedido_status}}</td>
                      </tr>
                    {% endfor %}
                </tbody>
            </table>
            
        </div> 
    </div> 
</div>




{% endblock %}

templates/clienteregistar.html
{% extends "base.html" %}

{% block title%} Registo Cliente {% endblock %}



{% block content%}
 <style>
     .errorlist{
         color: red;
         list-style: none;
     }
 </style>


                                        
<div class="container mt-5">
  
    <div  class="row">
        <h3>Registo</h3>
            <form action="" method="POST" >
                {% csrf_token %}
               {{form.as_p}}
               <button    class="btn btn-primary btn-danger" style="width: 250px; margin-left: 100px;"> Registar Cliente</button>
            </form>
            <p> faça o login  <a href="{% url 'lojaapp:clienteentrar' %}">Entrar</p> </a> 
    </div> 
</div>




{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title%} HOME{% endblock %}

<!DOCTYPE html>

{% block content%}                                       
<div class="container">
    <div  class="row">
        {% for lista in produto_list %}  
        <div class="col-md-4">
            <div class="mt-4">
                <div class="card m-8"> 
                    <h4 class="text-center"><a href=" {% url 'lojaapp:produtodetalhe' lista.slug %}"> {{lista.titulo }} </h4></a>
                      <img  class="ml-5" src="{{lista.image.url}}" width="150px">
                              <p class="m-4">PREÇO: <strike> € .{{lista.preco_mercado }}</strike> € {{lista.venda}}</p> 
                            <div class="text-left"> 
                                {% for cp in carro.carroproduto_set.all %}   {% endfor %}
                                <a href="{% url 'lojaapp:produtodetalhe' lista.slug %}"> <button class="btn btn-danger mr-5" type="button">Comprar</button> </a>  
                                <a href="{% url 'lojaapp:meucarro'  %}"> <button class="btn btn-danger " type="button" >Carrinho</button> </a>                   
                                 <a href="{% url 'lojaapp:meucarro'%}" class="btn btn-outline-danger btn-sm mt-1 "> + </a>
                                <a href="{% url 'lojaapp:meucarro'%}" class="btn btn-outline-danger btn-sm mt-1 "> - </a>
                                <a href="{% url 'lojaapp:meucarro'%}" class="btn btn-outline-danger btn-sm mt-1 " > x </a> 
                              <!--<div class="mr-1"> total:£{{carro.total}} </div>-->    
                             </div>
                            
                   </div>             
              </div>
          </div>
{% endfor %}
     </div> 
</div>
{% endblock %}

templates/meucarro.html
   {% extends 'base.html' %}
   {% block title%}MeuCarro{% endblock %}
  
   <!DOCTYPE html>
  {% block content %}
  
<div class="container">
        <div class="row">
            <div class="col-md-8">
                <h4>ITEM DO CARRINHO</h4>
                  <table class="table">
                       <thead>
                             <tr>
                                <th>Código</th> 
                                <th>Produto</th>  
                                <th>Preco</th>  
                                <th>Quantidade</th> 
                                <th>Subtotal</th>  
                                  
                             </tr>
                        </thead>
                        <tbody>  
                             {% for cp in carro.carroproduto_set.all %}
                                <tr>
                                  <td>{{forloop.counter}}</td>  
                                  <td>{{cp.produto.titulo}}</td> 
                                  <td>{{cp.avaliacao}}</td> 
                                  <td>{{cp.quantidade}}</td>   
                                  <td>{{cp.subtotal}}</td>     
                                </tr> 
                                
                                <td>
                                    <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=inc" class=" btn btn-outline-danger btn-sm mt-1"> + </a>
                                    <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=dcr" class=" btn btn-outline-danger btn-sm mt-1"> - </a>
                                    <a href="{% url 'lojaapp:manipularcarro' cp.id %}?acao=rmv" class=" btn btn-outline-danger btn-sm mt-1"> x </a>
                                </td>    
                             {% endfor %}
                              <tr>
                                  <th colspan="4" class="text-right"> Carrinho Total</th>
                                  <th>€:{{carro.total}} </th> 
                                  <tr>
                                    <th>
                                      {% if carro.carroproduto_set.all %}
                                      <a href="{% url 'lojaapp:limparcarro' %}"class=" btn btn-outline-danger"> Limpar Carrinho</a>
                                    </th>
                                    {% endif %}  
                                  </tr> 
                                  {% if carro.carroproduto_set.all %}
                                  <tr>
                                   <th> 
                                    <a href="{% url 'lojaapp:checkout' %}" class=" btn btn-outline-danger"> Processar Compra</a>
                                  </th>
                                   
                                  </tr>        
                                  {% endif %}
                         </tbody>    
                           
                  </table> 
                     
            </div>  
        </div>    

</div>


{% endblock %}

templates/pesquisa.html
{% extends "base.html" %}

{% block title%} pesquisa produtos{% endblock %}

<!DOCTYPE html>

{% block content%}                                       
<div class="container">
    <div  class="row">
        <div class="col-md-8">
           
            {% if result %}
            <h3> <span class="text-danger">{{request.GET.keyword}}</span></h3>
             {% else %} 
             <h3>Resultado da pesquisa não encontrado </h3>
            {% endif %}
            <br>
            {% for res in result %}
            <div class="row">
                <div class="col-md-8">
                    <img src="{{res.image.url}}"  class="img-fluid" >
                </div>
                <div class="col-md-4">
                 <h4 class="">{{res.titulo}}</h4>
                 <p>Preço €{{res.slug}}</p>
                 <p>{{res.descricao}}</p>
                 <p>Preço €{{res.venda}}</p>
                 <p>Preço €{{res.garantia}}</p>
                 <p>Preço €{{res.return_devolucao}}</p>
                </div>
            </div>
             
            {% endfor %}
                           
                     
        </div>
     </div> 
</div>

{% endblock %}

templates/processar.html
{% extends "base.html" %}
{% load static %} 
{% block title%}Processar Compra{% endblock %}
{% load static %} 
<!DOCTYPE html>

<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% block content%}


<div class="container ">
    <a href="{% url 'lojaapp:meucarro' %}" class=" btn btn-outline-danger btn-sm mt-3">Atualizar Carrinho </a>
    <table class="table border border-danger mt-4">
        <thead  class="border border-danger">
              <tr  class="border border-danger">
                 <th class="border border-danger ">Código</th> 
                 <th class="border border-danger">Produto</th>  
                 <th class="border border-danger">Avaliacao</th>  
                 <th class="border border-danger">Quantidade</th> 
                 <th class="border border-danger">Subtotal</th>  
                 <th class="border border-danger">Acao</th>      
              </tr>
         </thead>
         <tbody class="border border-danger">  
              {% for cp in carro.carroproduto_set.all %}
                 <tr  class="border border-danger">
                   <td  class="border border-danger">{{forloop.counter}}</td>  
                   <td  class="border border-danger">{{cp.produto.titulo}}</td> 
                   <td class="border border-danger">{{cp.avaliacao}}</td> 
                   <td class="border border-danger">{{cp.quantidade}}</td>   
                   <td class="border border-danger">{{cp.subtotal}}</td>     
                 </tr>
                {% endfor %} 
         </tbody>
         <tr  class="border border-danger">
            <th colspan="4" class="bg text-center border border-danger">Valor total</th>
            <th>£.{{carro.total}}</th>

         </tr>
     </table>            
     <div class=" text-center">
         <h3>Detalhe da Compra</h3>
             <form action="" method="POST">           
                {%csrf_token %}
                {{form.as_p}}
                 <button    class="btn btn-primary btn-danger" style="width: 300px;"> Compra</button>
              </form> 
       
        </div>
    </div>
   
        
      
</div>

                                   
{% endblock %}

templates/produtodetalhe.html
   {% extends 'base.html' %}
   {% block title%}TODOS PRODUTOS{% endblock %}
  
{% block content %}
            <div class="container">
                <h4>Produto: {{produto.titulo}}</h4><hr>  
                <div class="row">
                    <div class="col-md-6">
                        <img src="{{produto.image.url}} " alt="" class="img-fluid" width="380px">
                    </div>  
                    <div class=" col-md-6 text-left">
                        <h3>{{produto.titulo}} ( {{produto.visualizacao}} visualizações)<h3>
                        <h4>Categoria: {{produto.categoria}}<h4>
                            <h5 class="mt-3">Preço:<strike> € .{{produto.preco_mercado}}</strike> €. {{produto.venda}}</h5>
                            <a href="{% url 'lojaapp:addcarro' produto.id %}" class="btn btn-success">Comprar</a><hr>
                            <p class="text-danger"> Garantia:{{produto.garantia}}</p>
                            <p class="text-danger"> Politica Devolução:{{produto.return_devolucao}}</p><hr>
                            <p class="text-success">Descrição do Produto: {{produto.descricao}}</p>
                     </div>     
                </div>    
            </div>   
{% endblock %}

templates/todosprodutos.html
{% extends "base.html" %}
{% load static %} 
{% block title%} Todos Produtos{% endblock %}


<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
{% block content%}



                                        
<div class="container">

    {% for cat in  todoscategorias %}  
    <h1>{{cat.titulo}}</h1>
    <div  class="row">
        {% for lista in  cat.produto_set.all %}   
        <div class="col-md-4">
            <div class="mt-4">
                <div class="card">
                   
                    <h4 class="text-center"><a href=" {% url 'lojaapp:produtodetalhe' lista.slug %}"> {{lista.titulo }} </h4></a>
                      <img  class="text-center" src="{{lista.image.url}}" width="150">
                              <p class="m-4">PREÇO: <strike> € .{{lista.preco_mercado }}</strike> € {{lista.venda}}</p>             
                            <div class="text-center "> 
                                <a href="{% url 'lojaapp:meucarro'%}" class="btn btn-outline-danger">CARRINHO</a>
                                <button class="btn btn-outline-danger btn-sm mt-1">Comprar</button> 
                             </div>
                            </div>   
                  </div>
        </div>
{% endfor %}
</div> 
{% endfor %}
</div>
{% endblock %}